### ISSUE TITLE
Issues with naming conventions 

### ISSUE THREAD

**Issue by steventhomasmiller** [steventhomasmiller/ITC298-Final#1]
Hi Thomas,
I'm getting a couple of errors due to most likely due to my naming conventions. I was able to trace error one to both the viewPost and addPost files in my handlers folder, whereas error two is pointing to my home.js folder. I got kinda stumped, so I figured I would reach out.

![error1](https://cloud.githubusercontent.com/assets/6345723/8049830/56228da0-0e19-11e5-8e01-5c2682594c54.jpg)
![error2](https://cloud.githubusercontent.com/assets/6345723/8049829/561e43ee-0e19-11e5-9646-e742401e9774.jpg)

**Comment by steventhomasmiller** [comment]
Error two begins at "And so is the server." It almost looks as though they're one image in this thread.

**Comment by thomaswilburn** [comment]
The first problem, you're registering the same route twice. That's why it says that it conflicts with an existing route.

In the second error, check the error result coming from your call to the database. It looks to me like there's a problem. As a result, blogpost is null or undefined, not an array, and you can't call `foreach()` on a non-array value.
